FROM golang:1.24-alpine AS builder
RUN apk add --no-cache git make
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN cd cmd && CGO_ENABLED=0 GOOS=linux go build -o ../live-once-tech-task

FROM alpine:latest
RUN apk --no-cache add ca-certificates tzdata
WORKDIR /app
COPY --from=builder /app/live-once-tech-task .
COPY deployments/*.yml ./deployments/
EXPOSE 8080
CMD ["./live-once-tech-task"]